sudo: false
language: node_js
node_js:
  - "4.4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
script:
  - npm run travis
after_success:
  - npm run cover
cache:
  bundler: true
  directories:
    - node_modules
    - bower_components
git:
  depth: 10